
project_id = "ecvsnnfdaqjnbcpvxlly"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]

[db]
port = 54322

[studio]
enabled = true
port = 54323
api_url = "http://localhost"

[inbucket]
enabled = true
port = 54324

[storage]
enabled = true

[realtime]
enabled = true

[auth]
enabled = true

[functions.elevate-to-super-admin]
verify_jwt = true
